### ISSUE TITLE
Segmentation Fault 11 trying to enter Hectic

### ISSUE THREAD

**Issue by DieMatratze** [svkaiser/Doom64EX#21]
I initially posted this issue in Alexey Lysiuk's Doom64EX OS X build, but they suggested to post it here:

I used the secret exit in "Staging Area" to proceed to the level "Hectic." I was shown the text informing me I'd found Hectic (though the screen did not melt beforehand), but when I clicked to proceed, the game crashed. Using Terminal, I discovered the application underwent "Segmentation fault 11" when trying to transition. I attempted to use lldb to further diagnose the problem, but that wound up forcing me to restart my computer. Curiously, using the normal exit from "Staging Area" to "The Terraformer" worked just fine. Maybe it has something to do with Hectic's unusual level transition (there's no after-level stats screen; it goes straight to the intro text)? I'm including my crash log: [doom64ex_2016-05-29-164020.txt](https://github.com/svkaiser/Doom64EX/files/290021/doom64ex_2016-05-29-164020.txt)

"Only the best will reap its rewards" indeed. ;)

**Comment by dotfloat** [comment]
I have disabled the fire sky effect for the time being. The outside section has green sky now, but the level should otherwise be playable.

The issue is that the new Pixmap API isn't mature enough to handle raw unpalette'd images as I'm still trying to figure out the best way to design the whole thing.

I'll keep this issue open until the spooky sky is back in its rightful place.

**Comment by dotfloat** [comment]
Fixed.
