### ISSUE TITLE
Build instructions for Windows

### ISSUE THREAD

**Issue by Zero-Shift** [svkaiser/Doom64EX#39]
I've been trying pretty much all night to build this source on Windows to no avail, using multiple VC versions but nothing seems to work. It's just errors on errors on errors.

Which VC should I be using, and where should I put the external dependencies so CMake actually sees them?

Thanks!

**Comment by dotfloat** [comment]
Currently Windows support is a work in progress. It works, but there are a few minor packaging problems. If you just want to use an updated version of Doom64EX, you can [download it here](https://dl.dropboxusercontent.com/u/7122698/doom64ex-win32_test.zip). (It's a pre-pre alpha, hence why I'm being a tiny bit secretive)

To compile it yourself, you'll need:
- mingw-w64 32-bit [(Download)](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/6.2.0/threads-win32/dwarf/i686-6.2.0-release-win32-dwarf-rt_v5-rev1.7z/download)
- CMake 3.0+
- Doom64EX Dependencies [(Download)](https://dl.dropboxusercontent.com/u/7122698/mingw-w64-i686.7z)

Extract the dependencies into the `/extern/` directory, such that the following directories exist:
- `/extern/bin`
- `/extern/lib`
- `/extern/include`

Use CMake to generate MinGW Makefiles from the main CMakeLists.txt file and `make` it. You can also use IDEs with CMake support such as CLion (which is known to work), QtCreator, etc.

Sadly, Visual Studio's C++ Compiler is unsupported at this time because it lacks support for C++14 features.

If you have any further questions, feel free to ask.

**Comment by Zero-Shift** [comment]
Thanks, I had a feeling MinGW was the key to building this.

**Comment by dotfloat** [comment]
Didn't see your edits, sorry:

- Yes, you need to copy the .DLL files to the same directory as `doom64ex.exe`.
- SDL2.dll thing is fixed, but I haven't uploaded it.
- The texture problem can be fixed by recreating `doom64.wad` with the new built-in tool (`doom64ex.exe -wadgen <path to .z64>` in cmd). Doing it has other problems which I haven't ironed out yet.

I'll close this issue once I update the README.

**Comment by Zero-Shift** [comment]
Okay thanks!

One other issue: When using -wadgen, the created DOOMSND.SF2 doesn't seem to work or load properly. Here's the console output

`WARNING: CVar s_soundfont doesn't point to a file.Found SoundFont C:\Users\CENSORED\AppData\Roaming\\doom64ex\doomsnd.sf2
SoundFont file size mismatch`
`fluidsynth: error: Couldn't load soundfont file`
`fluidsynth: error: Failed to load SoundFont "C:\Users\CENSORED\AppData\Roaming\\doom64ex\doomsnd.sf2"
WARNING: I_InitSequencer: Failed to find soundfont file`

**Comment by dotfloat** [comment]
Could you try copying `doomsnd.sf2` to the location of the `.exe` and see if that helps?

**Comment by Zero-Shift** [comment]
Still no luck with that.

`S_Init: Setting up sound.`
`Found SoundFont doomsnd.sf2`
`SoundFont file size mismatch`
`fluidsynth: error: Couldn't load soundfont file`
`fluidsynth: error: Failed to load SoundFont "doomsnd.sf2"`
`WARNING: I_InitSequencer: Failed to find soundfont file`

The only way I can get sound is to use the old DOOMSND.SF2 from the old release build

**Comment by dotfloat** [comment]
Alright, thanks. I'm assuming that it has something to do with `SoundFont file size mismatch`. I'll have a closer look when I'm at a Windows PC.

**Comment by Zero-Shift** [comment]
That did the trick!

It still crashed when starting a new game on Hardcore! only once after compiling, here's the crash info in case you want it but it seems to be working fine for now:

`Faulting application name: doom64ex.exe, version: 0.0.0.0, time stamp: 0x57dae435`
`Faulting module name: doom64ex.exe, version: 0.0.0.0, time stamp: 0x57dae435`
`Exception code: 0xc0000005`
`Fault offset: 0x00054458`
`Faulting process id: 0x42f30`
`Faulting application start time: 0x01d20f7c95c2058d`
`Faulting application path: D:\Users\CENSORED\Doom\Doom64EX\New folder\doom64ex.exe`
`Faulting module path: D:\Users\CENSORED\Doom\Doom64EX\New folder\doom64ex.exe`
`Report Id: 46f6bc61-6694-414c-92af-3942112fa6bc`
`Faulting package full name: `
`Faulting package-relative application ID: `
